Update files in com.oracle.truffle.r.native/gnur/patch from GNU-R 4.0.3

diff --git a/com.oracle.truffle.r.native/gnur/patch/Makefile.in b/com.oracle.truffle.r.native/gnur/patch/Makefile.in
--- a/com.oracle.truffle.r.native/gnur/patch/Makefile.in
+++ b/com.oracle.truffle.r.native/gnur/patch/Makefile.in
@@ -82,7 +82,8 @@ vignettes: stamp-recommended
 
 ## This needs packages built, hence 'R' dependence on 'javaconf'
 ## javareconf gets remade often.
-stamp-java : etc/javaconf $(srcdir)/src/scripts/javareconf.in
+## If configure is re-run, etc/Makeconf gets reset to initial Java state
+stamp-java : etc/Makeconf etc/javaconf $(srcdir)/src/scripts/javareconf.in
 @WANT_JAVA_TRUE@	@$(ECHO) "configuring Java ..."
 @WANT_JAVA_TRUE@	@-bin/R CMD javareconf
 	@touch stamp-java
@@ -142,7 +143,7 @@ uninstall:
 	@for f in $(INSTFILES) $(NON_SVN_INSTFILES); do \
 	  rm -f "$(DESTDIR)$(rhome)/$${f}"; \
 	done
-	@rm -rf "$(DESTDIR)$(Rexecbindir)" "$(DESTDIR)$(rhome)/lib"
+	@rm -Rf "$(DESTDIR)$(Rexecbindir)" "$(DESTDIR)$(rhome)/lib"
 	@rmdir "$(DESTDIR)$(rhome)" 2>/dev/null \
           || $(ECHO) "  dir $(DESTDIR)$(rhome) not removed"
 	@rm -f "$(DESTDIR)${libdir}/libR$(R_DYLIB_EXT)"
@@ -158,15 +159,15 @@ distclean: clean
 	@(for d in $(SUBDIRS); do rsd="$${d} $${rsd}"; done; \
 	  for d in $${rsd}; do (cd $${d} && $(MAKE) $@); done)
 	@rm -f po/Makefile
-	-@rm -rf bin include lib library modules gnome
+	-@rm -Rf bin include lib library modules gnome
 	@if test -f non-tarball ; then \
 	  rm -f $(NON_SVN_INSTFILES) non-tarball doc/FAQ doc/RESOURCES doc/html/resources.html doc/html/NEWS.html; \
 	fi
 	@if test "$(BUILDDIR_IS_SRCDIR)" = no ; then \
 	  rm -f $(NON_SVN_INSTFILES); \
-	  rm -rf $(SUBDIRS) $(SUBDIRS_WITH_NO_BUILD); \
+	  rm -Rf $(SUBDIRS) $(SUBDIRS_WITH_NO_BUILD); \
 	fi
-	-@rm -rf libconftest.dSYM
+	-@rm -Rf libconftest.dSYM
 	-@rm -f Makeconf Makefile Makefile.bak Makefrag.* \
 	  config.cache config.log config.status libtool stamp-java \
 	  $(ACLOCAL_M4) acinclude.m4 $(distdir).tar.gz
@@ -175,9 +176,10 @@ maintainer-clean: distclean
 	@$(ECHO) "deletes files that may need special rules to rebuild"
 	@(for d in $(SUBDIRS); do rsd="$${d} $${rsd}"; done; \
 	  for d in $${rsd}; do (cd $${d} && $(MAKE) $@); done)
-	-@(cd $(srcdir) && rm -rf autom4te.cache)
+	-@(cd $(srcdir) && rm -Rf autom4te.cache)
 
 dist: dist-unix
+## GNU gzip 1.8 warns that env var GZIP is obsolescent for gzip, so use as arg
 dist-unix: distdir
 	-chmod -R a+r $(distdir)
 	-chmod -R go-w $(distdir)
@@ -186,11 +188,11 @@ dist-unix: distdir
           if test $(distdir) != $${dirname} ; then \
             mv $(distdir) $${dirname}; \
           fi ; \
-	  GZIP=$(GZIP) $(TAR) czf $${distname}.tar.gz $${dirname}; \
-	  rm -rf $${dirname}
+	  $(TAR) cf $${distname}.tar $${dirname} && $(R_GZIPCMD) $(GZIP) $${distname}.tar; \
+	  rm -Rf $${dirname}
 dist-win:
 distdir: $(DISTFILES) vignettes
-	@rm -rf $(distdir)
+	@rm -Rf $(distdir)
 	@mkdir $(distdir)
 	@-chmod 755 $(distdir)
 	@for f in $(DISTFILES); do \
@@ -219,6 +221,71 @@ distdir: $(DISTFILES) vignettes
 	  cp library/$${d}/doc/*.pdf $(distdir)/src/library/$${d}/inst/doc; \
 	done
 	@(cd $(distdir); tools/link-recommended)
+
+distcheck: distcheck-unix
+distcheck-unix: dist
+	distname=`$(srcdir)/tools/GETDISTNAME`; \
+	dirname=`$(ECHO) $${distname} | sed -e s/_.*//`; \
+	rm -Rf $${dirname}; \
+	$(R_GZIPCMD) -d -c $${distname}.tar.gz | $(TAR) -x -f -; \
+	chmod u+w $${dirname}; \
+	if test -f config.site; then \
+	  cp config.site $${dirname}; \
+	fi; \
+	mkdir $${dirname}/_build $${dirname}/_inst; \
+	test -d $${dirname}/_build || exit 0; \
+	dc_install_base=`cd $${dirname}/_inst && pwd` \
+	  && save__cwd=`pwd` \
+	  && cd $${dirname}/_build \
+	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
+	  && $(MAKE) \
+	  && $(MAKE) check-all \
+	  && $(MAKE) install \
+	  && $(MAKE) uninstall \
+	  && $(MAKE) distuninstallcheck_dir="$$dc_install_base" \
+	        distuninstallcheck \
+	  && $(MAKE) dist \
+	  && rm -f $${distname}.tar.gz \
+	  && $(MAKE) distcleancheck \
+	  && cd "$$save__cwd" \
+	  || exit 1; \
+	rm -Rf $${dirname}; \
+	$(ECHO) "$${distname}.tar.gz ready for distribution"
+
+distcheck-win:
+distuninstallcheck:
+	@test -n '$(distuninstallcheck_dir)' || { \
+	  echo 'ERROR: trying to run $@ with an empty' \
+	       '$$(distuninstallcheck_dir)' >&2; \
+	  exit 1; \
+	}; \
+	cd '$(distuninstallcheck_dir)' || { \
+	  $(ECHO) 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
+	  exit 1; \
+	}; \
+	test `find . -type f -print | wc -l` -eq 0 || \
+	  { $(ECHO) "ERROR: files left after uninstall:" ; \
+	    `find . -type f -print`; \
+	    exit 1; } >&2
+distcleancheck: distclean
+	@test `find . -type f -print | wc -l` -eq 0 || \
+	  { $(ECHO) "ERROR: files left in build directory after distclean:" ; \
+	    `find . -type f -print`; \
+	    exit 1; } >&2
+
+## For developers: from an svn checkout expect .svn to be only in the srcdir
+checkdistcomplete:
+	@distname=`$(srcdir)/tools/GETDISTNAME`; \
+	dirname=`$(ECHO) $${distname} | sed -e s/_.*//`; \
+	if test -d $${dirname}; then \
+	  echo "Please remove directory $${dirname} first"; \
+	  exit 1; \
+	fi; \
+	rm -Rf $${dirname}; \
+	echo "Checking $${distname}.tar.gz"; \
+	$(R_GZIPCMD) -d -c $${distname}.tar.gz | $(TAR) -x -f -; \
+	diff -r $${dirname} $(srcdir) | grep "^Only in $(srcdir)" | grep -v "^Only in.*[.]svn"; \
+	rm -Rf $${dirname}
 
 info pdf:
 	-@(cd doc && $(MAKE) $@)
