During build, print paths to gnur build logs

diff --git a/com.oracle.truffle.r.native/gnur/Makefile.gnur b/com.oracle.truffle.r.native/gnur/Makefile.gnur
--- a/com.oracle.truffle.r.native/gnur/Makefile.gnur
+++ b/com.oracle.truffle.r.native/gnur/Makefile.gnur
@@ -100,6 +100,10 @@ RECPKGS := "--without-recommended-packages"
 endif
 
 GNUR_HOME_BINARY_UNPACKED_PARENT := $(dir $(GNUR_HOME_BINARY_UNPACKED))
+GNUR_CONFIG_LOG = $(GNUR_HOME_BINARY_UNPACKED)/gnur_configure.log
+GNUR_MAKE_LOG = $(GNUR_HOME_BINARY_UNPACKED)/gnur_make.log
+$(info GNUR_CONFIG_LOG = $(GNUR_CONFIG_LOG))
+$(info GNUR_MAKE_LOG = $(GNUR_MAKE_LOG))
 
 ifdef BUILD_GNUR
 $(GNUR_HOME_BINARY_UNPACKED)/gnur.done:
@@ -107,7 +111,18 @@ $(GNUR_HOME_BINARY_UNPACKED)/gnur.done:
 	rm -rf $(GNUR_HOME_BINARY_UNPACKED)
 	mkdir -p $(GNUR_HOME_BINARY_UNPACKED_PARENT)
 	(cd $(GNUR_HOME_BINARY_UNPACKED_PARENT); tar xf R-$(R_VERSION).tar.gz)
-	(cd $(GNUR_HOME_BINARY_UNPACKED); ./configure --with-x=no --with-aqua=no --with-pcre2 $(RECPKGS) $(OS_EXTRA_CONFIGURE_FLAGS) --enable-memory-profiling $(GNUR_CONFIG_FLAGS) > gnur_configure.log 2>&1; $(MAKE) -j > gnur_make.log 2>&1)
+	(\
+		cd $(GNUR_HOME_BINARY_UNPACKED);\
+		./configure --with-x=no --with-aqua=no --with-pcre2 $(RECPKGS) $(OS_EXTRA_CONFIGURE_FLAGS) --enable-memory-profiling $(GNUR_CONFIG_FLAGS) > $(GNUR_CONFIG_LOG) 2>&1;\
+		$(MAKE) -j > $(GNUR_MAKE_LOG) 2>&1\
+	) || (\
+	  	# Print tails of both logs if configure or make fails\
+		echo "=== Last 50 lines of gnur_configure.log: ===";\
+		tail -n 50 $(GNUR_CONFIG_LOG) 2>/dev/null || echo "";\
+		echo "=== Last 50 lines of gnur_make.log: ===";\
+		tail -n 50 $(GNUR_MAKE_LOG) 2>/dev/null || echo "";\
+		echo "=== End of last 50 lines of gnur_make.log ===";\
+	)
 	touch $(GNUR_HOME_BINARY_UNPACKED)/gnur.done
 else
 $(GNUR_HOME_BINARY_UNPACKED)/gnur.done:
