configure_fastr: overhaul of the GCC runtime libs check on Linux

diff --git a/com.oracle.truffle.r.native/run/configure_fastr b/com.oracle.truffle.r.native/run/configure_fastr
--- a/com.oracle.truffle.r.native/run/configure_fastr
+++ b/com.oracle.truffle.r.native/run/configure_fastr
@@ -108,16 +108,45 @@ fi
 
 (
   if [[ "$OSTYPE" == "linux-gnu" ]]; then
-    echo "int main(){}" | gcc -x c -Wl,--no-as-needed -lgfortran -lgcc_s -lquadmath -o /dev/null - > /dev/null 2>/dev/null
-    res=$?
+    res=0
+    for lib in libgfortran.so.3 libm.so.6 libquadmath.so.0 libgcc_s.so.1; do
+      if ! ldconfig -p | grep --quiet $lib; then
+        echo "Error: could not find gfortran3 runtime library: $lib"
+        echo "Please install the gfortran3 runtime libraries:"
+        echo "    On Debian based systems: apt-get install libgfortran3"
+        echo "    On Oracle Linux 7: yum install libgfortran"
+        echo "    On Oracle Linux 8: yum install compat-libgfortran-48"
+        res=1
+        break
+      fi
+    done
+    if ! ldconfig -p | grep --quiet "libgomp.so.1"; then
+      echo "Error: could not find OpenMP runtime library: libgomp.so.1"
+      echo "Please install the OpenMP runtime library runtime libraries:"
+      echo "    On Debian based systems: apt-get install libgomp1"
+      echo "    On Oracle Linux 7 and 8: yum install libgomp"
+      echo "    Note: Oracle Linux 8 should contain libgomp by default"
+      res=1
+    fi
+    if which gfortran > /dev/null 2> /dev/null; then
+      echo "Note: if you intend to install R packages with Fortran 90 and newer code, you need to install gfortran compiler."
+      echo "Fortran 77 or any Fortran code that is compilable by the 'f2c' tool does not require gfortran compiler."
+      echo "You can install the gfortran compiler with:"
+      echo "    On Debian based systems: apt-get install build-essential"
+      echo "    On Oracle Linux 7: yum groupinstall 'Development Tools'"
+      echo "    On Oracle Linux 8: yum groupinstall 'Development Tools'"
+      if [[ $res != 0 ]]; then
+        echo "Caution: you still need to install gfortran3 runtime libraries on all systems where this version is not the default (Ubuntu 18 or higher, Oracle Linux 8 or higher)."
+      fi
+    fi
     if [[ $res != 0 ]]; then
-      echo "Cannot build a simple C program linking with libgfortran, libgcc_s, and libquadmath."
-      echo "Please install GCC and gfortran using:"
-      echo "    On Debian based systems: sudo apt-get install build-essential gfortran"
-      echo "    On CentOS/RHEL/Oracle Linux: sudo yum groupinstall \"Developent Tools\"; yum install gcc-gfortran"
-	  echo ""	
-      printHelp
+      echo "The basic configuration of FastR failed."
+      echo "To learn more:"
+      echo "  run this script with '--help'"
+      echo "  visit https://www.graalvm.org/docs/reference-manual/languages/r"
       exit 1
+    else
+      echo "The basic configuration of FastR was successfull."
     fi
   elif [[ "$OSTYPE" == "darwin"* ]]; then
     cd -P "$( dirname "$source" )/../lib"
