Do not include GCC runtime libraries in the distribution

diff --git a/com.oracle.truffle.r.native/run/configure_fastr b/com.oracle.truffle.r.native/run/configure_fastr
--- a/com.oracle.truffle.r.native/run/configure_fastr
+++ b/com.oracle.truffle.r.native/run/configure_fastr
@@ -37,6 +37,46 @@ while [ -h "$source" ] ; do
 done
 
 (
+  if [[ "$OSTYPE" == "linux-gnu" ]]; then
+    echo "int main(){}" | gcc -x c -Wl,--no-as-needed -lgfortran -lgcc_s -lquadmath -o /dev/null - > /dev/null 2>/dev/null
+    res=$?
+    if [[ $res != 0 ]]; then
+      echo "Cannot build simple C program linking with libgfortran, libgcc_s, and libquadmath."
+      echo "Please install GCC using:"
+      echo "    On Debian based systems: apt-get install build-essential"
+      echo "    On CentOS/RHEL: yum groupinstall \"Developent Tools\""
+    fi
+  elif [[ "$OSTYPE" == "darwin"* ]]; then
+    cd -P "$( dirname "$source" )/../lib"
+    # correct paths on Mac OSX
+    GFORTRAN_LIBRARIES="libgfortran.3.dylib libquadmath.0.dylib"
+    GFORTRAN_LOCATIONS="$* /opt/local/lib /opt/local/lib/libgcc /usr/local/gfortran/lib none"
+    for GFORTRAN_LIB in $GFORTRAN_LIBRARIES
+    do
+      if [ ! -f "${GFORTRAN_LIB}" ]; then
+        for LOCATION in $GFORTRAN_LOCATIONS
+        do
+          if test -f "${LOCATION}/${GFORTRAN_LIB}"; then
+            LIB_LOCATION="${LOCATION}/${GFORTRAN_LIB}"
+            break
+          elif [ "$LOCATION" = "none" ] ; then
+            echo "${GFORTRAN_LIB} not found"
+            echo "Please ensure that you have gfortran installed on your system, e.g., using homebrew or MacPorts."
+            echo "If ${GFORTRAN_LIB} is installed in a non-standard location, you can supply additional locations"
+            echo "as parameters to the configure_fastr tool as command line arguments."
+            exit 1
+          fi
+        done
+        echo "${GFORTRAN_LIB} found at ${LIB_LOCATION}"
+        ln -s "$LIB_LOCATION" "$GFORTRAN_LIB"
+      fi
+    done
+  else
+    echo "Unknown operating system."
+    echo "FastR may still work."
+    echo "Make sure that GCC including gfortran and OpenMP is installed on your system."
+  fi
+
   export GRAALVM_VERSION=`grep -o 'GRAALVM_VERSION=.*' "$( dirname "$source" )/../../../../release" | cut -d= -f2`
   cd -P "$( dirname "$source" )/../etc"
   ./configure --with-x=no --with-aqua=no --enable-memory-profiling FFLAGS=-O2 $@
