Improve output of recommended packages API check.

diff --git a/com.oracle.truffle.r.native.recommended/Makefile b/com.oracle.truffle.r.native.recommended/Makefile
--- a/com.oracle.truffle.r.native.recommended/Makefile
+++ b/com.oracle.truffle.r.native.recommended/Makefile
@@ -85,19 +85,19 @@ ifdef FASTR_RECOMMENDED_BINARY
 $(info Using FastR recommended packages binary: $(FASTR_RECOMMENDED_BINARY))
 
 install.recommended: $(GNUR_RECOMMENDED_TARS)
-#	if ! (mx -p $(FASTR_R_HOME) r-pkgcache --print-api-checksum --vm fastr | tail -n 1 | diff -q $(FASTR_RECOMMENDED_BINARY)/api-checksum.txt -); then \
-#		echo "******************************"; \
-#		echo "ERROR:"; \
-#		echo "The checksum of FastR header files does not match the checksum that the recommended packages were build against."; \
-#		echo "You can run appropriate CI jobs in FastR repo to generate a new version of recommended packages binary and then upload it to the appropriate place."; \
-#		echo "******************************"; \
-#		echo "Actual checksum of FastR headers:"; \
-#		echo "$(mx -p $(FASTR_R_HOME) r-pkgcache --print-api-checksum --vm fastr)"; \
-#		echo "Expected checksum by the recommended pkgs:"; \
-#		cat $(FASTR_RECOMMENDED_BINARY)/api-checksum.txt; \
-#		echo "******************************"; \
-#		exit 1; \
-#	fi
+	@if ! (mx -p $(FASTR_R_HOME) r-pkgcache --print-api-checksum --vm fastr | tail -n 1 | diff -q $(FASTR_RECOMMENDED_BINARY)/api-checksum.txt -); then \
+		echo "******************************"; \
+		echo "ERROR:"; \
+		echo "The checksum of FastR header files does not match the checksum that the recommended packages were build against."; \
+		echo "You can run appropriate CI jobs in FastR repo to generate a new version of recommended packages binary and then upload it to the appropriate place."; \
+		echo "******************************"; \
+		echo "Actual checksum of FastR headers:"; \
+		mx -p $(FASTR_R_HOME) r-pkgcache --print-api-checksum --vm fastr; \
+		echo "Expected checksum by the recommended pkgs:"; \
+		cat $(FASTR_RECOMMENDED_BINARY)/api-checksum.txt; \
+		echo "******************************"; \
+		exit 1; \
+	fi
 	cp -R $(FASTR_RECOMMENDED_BINARY)/pkgs/* $(FASTR_R_HOME)/library
 	touch install.recommended
 
